# Example of xrayhelper config
xrayHelper:
    # Required, Default value: xray, your core type, support xray, v2ray, sing-box, clash, clash.premium, clash.meta
    coreType: xray
    # Required, absolute path to your core
    corePath: /data/adb/xray/bin/xray
    # Required, absolute path to your core config, can be a directory or single file
    coreConfig: /data/adb/xray/confs/
    # Required, absolute path to xrayhelper data directory, include a lot of data of xrayhelper
    # such as core geodate, v2rayNg's standard subscribe node share url and clash/clash.premium/clash.meta subscribe config
    dataDir: /data/adb/xray/data/
    # Required, absolute path to xrayhelper temp directory, include xrayhelper logs, core pid, core logs and so on
    runDir: /data/adb/xray/run/
    # Required for xray/v2ray/sing-box, Default value: proxy, the replaced outbound object's tag when you use xrayhelper to switch proxy node
    proxyTag: proxy
    # Optional, your subscribe url, support SSR, SIP002, v2rayNg standard share url
    # and also support clash/clash.premium/clash.meta config url, but you need add a prefix "clash+"
    subList:
        - https://testsuburl.com
        - clash+https://testclashsuburl.com
proxy:
    # Required, Default value: tproxy, proxy method you want to use, support tproxy, tun, tun2socks
    # If you use tun mode, please make sure your core support tun, and configure it correctly
    # If you use tun2socks mode, please run command "xrayhelper update tun2socks" to install tun2socks first
    # Usually tproxy has better performance and tun has better udp compatibility
    method: tun2socks
    # Required for tproxy, Default value: 65535, port of core tproxy inbound
    tproxyPort: 65535
    # Required for tun2socks, Default value: 65534, port of core socks5 inbound
    socksPort: 65534
    # Required for tun/tun2socks proxy method, Default value: xtun, marked traffic will be forwarded to this network device in tun/tun2socks mode
    tunDevice: xtun
    # Required, Default value: false, enable ipv6 proxy, need your proxy server support proxy ipv6 traffic
    enableIPv6: false
    # Required, Default value: blacklist, application package list proxy mode, support blacklist, whitelist
    # blacklist mode, application traffic in pkgList will be bypassed, others will be marked
    # whitelist mode, application traffic in pkgList will be marked, others will be bypassed
    # Special, if pkgList is empty, all application traffic will be marked whatever which proxy mode you use
    mode: whitelist
    # Optional, application package list, format is "apk_package_name:user", if the user value is omitted, it will be "0", aka the phone owner
    pkgList:
        - com.kiwibrowser.browser
        - com.termux:20
    # Optional, ap interface list, external traffic from apList will be marked
    apList:
        - wlan2
        - rndis0
    # Optional, ignore interface list, internal traffic from ignoreList will be bypassed
    ignoreList:
        - wlan+
    # Optional, intranet CIDR address list, by default, most intranet ip will be bypassed, add CIDR address to intraList if you want mark these traffic
    intraList:
        - 192.168.123.0/24
        - fd12:3456:789a:bcde::/64
clash:
    # Required for clash/clash.premium/clash.meta, Default value: 65533, all dns request will be redirected to the port which listen by clash/clash.premium/clash.meta
    dnsPort: 65533
    # Optional, if not empty, the template config will replace (or inject to) the actual clash/clash.premium/clash.meta config
    template: /data/adb/xray/clashconfs/template.yaml
