xrayHelper:
    core: /data/adb/xray/bin/xray
    coreConfig: /data/adb/xray/confs/
    runDir: /data/adb/xray/run
proxy:
    method: tproxy
    tproxyPort: 65535
    enableIPv6: false
    mode: whitelist
    pkgList:
        - com.kiwibrowser.browser
    apList:
        - wlan2
        - rndis0
