xrayHelper:
    coreType: xray
    corePath: /data/adb/xray/bin/xray
    coreConfig: /data/adb/xray/confs/
    dataDir: /data/adb/xray/data/
    runDir: /data/adb/xray/run/
    proxyTag: proxy
    subList:
        - https://testsuburl.com
proxy:
    method: tproxy
    tproxyPort: 65535
    socksPort: 65534
    enableIPv6: false
    mode: whitelist
    pkgList:
        - com.kiwibrowser.browser
        - com.termux:20
    apList:
        - wlan2
        - rndis0
    ignoreList:
        - ignore
    intraList:
        - 192.168.123.0/24
        - fd12:3456:789a:bcde::/64
clash:
    dnsPort: 65533
    template: /data/adb/xray/clashconfs/template.yaml
