xrayHelper:
    coreType: xray
    corePath: /data/adb/xray/bin/xray
    coreConfig: /data/adb/xray/confs/
    geodataDir: /data/adb/xray/
    runDir: /data/adb/xray/run/
proxy:
    method: tproxy
    tproxyPort: 65535
    enableIPv6: false
    mode: whitelist
    pkgList:
        - com.kiwibrowser.browser
        - com.termux
    apList:
        - wlan2
        - rndis0
